aggregator:
  settings:
    best_state_path: save/torch_cnn_cifar100_best.pbuf
    db_store_rounds: 1
    init_state_path: save/torch_cnn_cifar100_init.pbuf
    last_state_path: save/torch_cnn_cifar100_last.pbuf
    log_metric_callback:
      template: src.cifar100_utils.write_metric
    rounds_to_train: 100
    write_logs: false
  template: openfl.component.Aggregator
assigner:
  settings:
    task_groups:
    - name: train_and_validate
      percentage: 1.0
      tasks:
      - aggregated_model_validation
      - train
      - locally_tuned_model_validation
  template: openfl.component.RandomGroupedAssigner
collaborator:
  settings:
    db_store_rounds: 1
    delta_updates: false
    opt_treatment: RESET
  template: openfl.component.Collaborator
compression_pipeline:
  settings: {}
  template: openfl.pipelines.NoCompressionPipeline
data_loader:
  settings:
    batch_size: 256
    collaborator_count: 3
    data_group_name: cifar100
  template: src.ptcifar100_inmemory.PyTorchCIFAR100InMemory
network:
  settings:
    agg_addr: atsnode12
    agg_port: 52424
    cert_folder: cert
    client_reconnect_interval: 5
    disable_client_auth: false
    hash_salt: auto
    tls: false
  template: openfl.federation.Network
task_runner:
  settings: {}
  template: src.pt_cnn.PyTorchCNN
tasks:
  aggregated_model_validation:
    function: validate
    kwargs:
      apply: global
      metrics:
      - acc
  locally_tuned_model_validation:
    function: validate
    kwargs:
      apply: local
      metrics:
      - acc
  settings: {}
  train:
    function: train_batches
    kwargs:
      epochs: 1
      metrics:
      - loss